### ISSUE TITLE
Error after updating. KeyError: 'Model_1'

### ISSUE THREAD

**Issue by gazm2k5** [GivEnergy/giv_tcp#52]
My instance of watchtower automatically updated some containers overnight, and now GivTCP won't find my inverter.

```
2024-08-18T09:45:51.181994218Z 2024-08-18 10:45:51,181 - startup - [INFO] - ========================== STARTING GivTCP================================

2024-08-18T09:45:53.183548847Z 2024-08-18 10:45:53,183 - startup - [INFO] - Searching for Inverters

2024-08-18T09:45:53.183611228Z 2024-08-18 10:45:53,183 - startup - [INFO] - Scanning network for GivEnergy Devices...

2024-08-18T09:46:19.850718273Z 2024-08-18 10:46:19,850 - startup - [INFO] - No inverters found...

2024-08-18T09:46:19.859795964Z 2024-08-18 10:46:19,859 - startup - [INFO] - Setting up invertor: 1

2024-08-18T09:46:19.875438945Z Traceback (most recent call last):

2024-08-18T09:46:19.875484450Z   File "/app/startup.py", line 556, in <module>

2024-08-18T09:46:19.875861437Z     createsettingsjson(inv)

2024-08-18T09:46:19.875874394Z   File "/app/startup.py", line 174, in createsettingsjson

2024-08-18T09:46:19.876016222Z     outp.write("    inverter_type=\""+str(setts["Model_"+str(inv)])+"\"\n")

2024-08-18T09:46:19.876065959Z                                           ~~~~~^^^^^^^^^^^^^^^^^^^

2024-08-18T09:46:19.876077198Z KeyError: 'Model_1'

2024-08-18T09:46:21.933319804Z 2024-08-18 10:46:21,933 - startup - [INFO] - ========================== STARTING GivTCP================================

2024-08-18T09:46:23.935024631Z 2024-08-18 10:46:23,934 - startup - [INFO] - Searching for Inverters

2024-08-18T09:46:23.935111677Z 2024-08-18 10:46:23,934 - startup - [INFO] - Scanning network for GivEnergy Devices...

2024-08-18T09:46:51.258789828Z 2024-08-18 10:46:51,258 - startup - [INFO] - No inverters found...

2024-08-18T09:46:51.265682420Z 2024-08-18 10:46:51,265 - startup - [INFO] - Setting up invertor: 1
```

Reverted back to the old version for now, which has solved the issue.
```
givtcp:
    container_name: givtcp
    image: britkat/giv_tcp-ma:2.4.2
    restart: unless-stopped
    ports:
      - "6345:6345"                   # REST (add increments for each inverter)
      - "3005:3005"                   # This should match the WEB_DASH_PORT ENV below
    environment:
      - TZ=Europe/London
      - NUMINVERTORS=1
      - INVERTOR_IP_1=192.168.[redacted]
      - INVERTOR_AIO_1=True
      - INVERTOR_AC_1=False
      - NUMBATTERIES_1=0              # Number of battery modules installed and connected to the above inverter
      - MQTT_OUTPUT=True              # "True" if you want to publish your data to MQTT, "False" otherwise
      - MQTT_ADDRESS=mosquitto
      - MQTT_USERNAME=[redacted]
      - MQTT_PASSWORD=[redacted]
      - MQTT_TOPIC=GivEnergy/Data     # Root topic to publish data to. If left blank it will default to GivEnergy/<invertor_serial_number>
      - MQTT_PORT=1883                # Port of your existing broker, leave as "1883" for internal broker
      - HA_AUTO_D=True
      - LOG_LEVEL=Error
      - HOSTIP=192.168.[redacted]
      - WEB_DASH=True                 # Enable the wed dashboard
      - WEB_DASH_PORT=3005            # Port to serve the web dashboard on
    volumes:
      - /docker-volumes/givenergy/config:/config/GivTCP
    privileged: true
```

**Comment by G6EJD** [comment]
What setting did you make for inverter type ?

**Comment by G6EJD** [comment]
Did you use the givtcp configurator? check your log file

**Comment by gazm2k5** [comment]
> What setting did you make for inverter type ?

All my settings are above. I've deployed as a container, and have not used a Home Assistant addon as I don't run HA OS. I don't know what the configurator is, I'm assuming that's the front end configuration page you get in Home Assistant?
